### ISSUE TITLE
getLANIP is often incorrect

### ISSUE THREAD

**Issue by ThomWright** [momentumft/navy#48]
`getLANIP` always returns `127.0.1.1` for me, and at least one other linux user.

It seems to work for some OSX users, but for some it returns something else, e.g. a virtualbox IP.

Would something like this be better:

```js
const interfaceName = "wlan0" // supplied by user

const interfaces = os.networkInterfaces();
const networkInterface = interfaces[interfaceName]
for (const i in networkInterface) {
  var address = networkInterface[i];
  if (address.family === 'IPv4') {
    console.log(address.address);
  }
}
```

It does require the user to input which `interfaceName` to use though.

**Comment by madjam002** [comment]
The idea of `use-lan-ip` was to have a "no configuration necessary" command to get up and running.
If we're going to prompt the user for an interface, then they may as well use `navy config set external-ip [ip address here]` and get the IP themselves.

Just to confirm, you say this issue is happening for people on macOS? What's the output of `hostname -I` on your machine?

**Comment by ThomWright** [comment]
```
$ hostname -I
10.16.3.95 172.21.0.1 172.17.0.1 172.19.0.1 172.18.0.1 
```

Won't `navy config set external-ip [ip address here]` be overridden by whatever `getLANIP()` returns here: [lan-ip.js](https://github.com/momentumft/navy/blob/a922d86851e89110aa90c316b7209bfefbce3a67/packages/navy/src/cli/lan-ip.js)?
